version: '3.9'
networks:
  laravel-docker:

services:

  server:
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      php:
        condition: service_started
    container_name: laravel-server
    networks:
      - laravel-docker

  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: laravel-php
    networks:
      - laravel-docker

  mysql:
    image: mysql:8.0.36
    restart: unless-stopped
    container_name: laravel-mysql
    env_file:
      - ./mysql/.env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-docker
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:

